# ==========================================
# OPTCG Deck Builder - Application Config
# ==========================================

# Server
server.port=8085

# Perfil por defecto para desarrollo local
spring.profiles.default=mysql

# ==========================================
# JWT
# ==========================================
app.jwt.secret=optcg-deck-builder-tfg-secret-key-must-be-at-least-256-bits-long-2024
app.jwt.expiration=86400000

# ==========================================
# Spring Cache
# ==========================================
spring.cache.type=simple

# ==========================================
# API Externa - Cartas One Piece TCG
# ==========================================
# Base URL para la API externa de cartas
# Esta API es la fuente de verdad para todos los datos de cartas
# Los mazos y colecciones locales solo almacenan IDs externos
optcg.api.base-url=https://optcgapi.com

# ==========================================
# Cloudinary (Avatares)
# ==========================================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# ==========================================
# CORS (para Angular en dev)
# ==========================================
app.cors.allowed-origins=http://localhost:4200

# ==========================================
# Logging
# ==========================================
logging.level.com.optcg=DEBUG
logging.level.org.springframework.security=INFO

# Para simular el envio correos
resend.api.key=${RESEND_API_KEY}


# ==========================================
# Correo (Email Receipt) Puerto 465 para Railway
# ==========================================
# spring.mail.host=smtp.resend.com
# spring.mail.port=465
# spring.mail.username=${SMTP_USERNAME}
# spring.mail.password=${SMTP_PASSWORD}
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=false
# spring.mail.properties.mail.smtp.ssl.enable=true
# spring.mail.properties.mail.smtp.socketFactory.port=465
# spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
# spring.mail.properties.mail.smtp.connectiontimeout=5000
# spring.mail.properties.mail.smtp.timeout=5000
# spring.mail.properties.mail.smtp.writetimeout=5000